config/routes.rb
Rails.application.routes.draw do
  get 'votes/index'
  resources :replies
  resources :comments
  resources :activities do
    
    member do
      post 'upvote'
      delete 'downvote'
    end
  end
  namespace :admin do
    get 'users/index'
  end
  resources :relationships
  resources :words

  
  namespace :admin do
    resources :users do
      member do
        patch 'add'
        patch 'remove'
      end
    end
    resources :categories do
      resources :words
    end
  end
  
  resources :categories
  
  resources :lessons do
    resources :answers
  end
  resources :sessions
  resources :users do
    get 'dashboard'
    get 'liked_by'
    member do
      get 'following'
      get 'followers' 
    end
  end
  root 'pages#home'
  get 'categories/index'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
  default_scope { order(created_at: :desc) }
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  has_many :lessons, dependent: :destroy
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  has_many :answers, dependent: :destroy
  # validates :is_correct, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  has_many :replies

  validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity, as: :action, dependent: :destroy
  def correct_answers
    choices.where(is_correct: true).count
  end
  
  def next_word
    (category.words - words).first
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_one :activity, as: :action, dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }

  #REGEX = regular expression
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
            length: { maximum: 255 },
            format:{ with: EMAIL_REGEX},
            uniqueness: { case_sensitive: false}
  
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true

  mount_uploader :avatar, AvatarUploader
  has_many :lessons, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies
  def follow(other_user)
    Relationship.create(
      follower_id: id,            #current_user.id
      followed_id: other_user.id  #@user.id
    )
  end

  def active_relationships
    Relationship.where(follower_id: id)
  end


  def relationship(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def passive_relationships
    Relationship.where(followed_id: id)
  end

  def followers
    ids = passive_relationships.pluck(:follower_id)
    User.where(id: ids)
  end

  def following
    ids = active_relationships.pluck(:followed_id)
    User.where(id: ids)
  end
  
  def feed
    ids = following.pluck(:id)
    ids << id      #append | add the user_id to the array
    Activity.where(user_id: ids)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  validate :only_one_is_checked

  validates :content,presence: true, length: { maximum: 50 }
  private

  # validates choices: :content,uniqueness: { case_sensitive: false}
    def only_one_is_checked
      if choices.select{ |choice| choice.is_correct == true }.count !=1
        return errors.add :base, "Must have one correct choice"
      end
    end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :admin
  
  def index
    @category = Category.find(params[:category_id])
    @words = Word.where(category_id: params[:category_id]).paginate(page: params[:page], per_page: 10)
  end

  def new
    @category = Category.find(params[:category_id])
    @word = Word.new
    3.times { @word.choices.build }
  end

  def create
    @category = Category.find(params[:category_id])
    @word = @category.words.new(word_params)

    if @word.save
      flash[:success] = "Word and Choices created!"
      redirect_to admin_category_words_url
    else
      render 'new' 
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @word = Word.find(params[:id])

    if @word.update_attributes(word_params)
      flash[:success] = "Word and Choices updated!"
      redirect_to edit_admin_category_word_url
    else
      render 'edit'
    end
  end

  def destroy
    @word = Word.find(params[:id])
    if @word.destroy
      flash[:info] = "Word deleted."
      redirect_to request.referrer
    end
  end

  
  private
  def admin
    if !current_user.is_admin?
      flash[:danger] = "You can't access admin pages."
      redirect_to user_dashboard_url(current_user)
    end
  end

  def word_params
    params.require(:word).permit(:content, choices_attributes: [:id, :content, :is_correct])
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def index
    @cate = params[:cate]
    @category = Category.find_by(title: params[:cate])
    if @cate
      @lessons = Lesson.where(category_id: @category.id)
    else
      @lessons = Lesson.where(user_id: current_user.id)
    end
    
    # @answers = @lessons.answers
    @categories = Category.all
    # @words = @categories.words
    
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out(user)
    session.delete(:user_id)
  end

  def logged_in?              #return true if current/user is not nil
    !current_user.nil?        #check if current_user is not nill
  end
  
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_error.html.erb
<% if @word.errors.any?%>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong><%= pluralize(@word.errors.count, "error") %></strong> 
        <ul>
        <% @word.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
        
    </div>
    
<% end %>

app/views/admin/words/_form.html.erb
<%= form_for ([:admin, @category, @word]) do |f| %>
    <%= render 'error'%>
    <div class="form-group row">
        <div class="col-sm-3">
            <%= f.label :content %>
        </div>
        <div class="col-sm-7">
            <%= f.text_field :content, class: 'form-control' %>
        </div>
        
    </div>
    <div class="form-group row">
        <div class="col-sm-3">
            <%= f.label :choices %>
        </div>
        <div class="col-sm-9">
            <%= f.fields_for :choices do |choice| %>
                <div class="form-group row">
                    <div class="col-sm-9">
                        <%= choice.text_field :content, class: 'form-control' %>
                    </div>
                    <div class="col-sm-3">
                        <%= choice.label :is_correct do %>
                        Correct
                        <%= choice.check_box :is_correct %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>

    </div>

    <div class="form-group text-center">
        <%= f.submit 'Save Word',class: 'btn btn-success'%>
    </div>
<% end %>

app/views/admin/words/edit.html.erb
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <span>Admin | <%= @category.title %> | Words | Edit</span>
                </div>
                <div class="col-sm-6 text-right">
                    <%= link_to "Back",admin_category_words_path(@category)%>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="container w-75">
                <%= render 'form'%>
            </div>
        </div>
    </div>
</div>

app/views/admin/words/index.html.erb
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <span>Admin | <%= @category.title %> | Words</span>
                </div>
                <div class="col-sm-6 text-right">
                    <%= link_to "Add Word", new_admin_category_word_path , class: "btn btn-sm btn-success"%>
                    
                    <%= link_to "Back",admin_categories_path%>
                </div>
            </div>
        </div>

        <div class="card-body">
            <h2><%= @category.title%></h2>
            <p><%= @category.description%></p>
        
            <table class="table">
                <tr>
                    <th>Words</th>
                    <th>Answer</th>
                    <th>Action</th>
                </tr>
                <% @words.each do |word|%>
                <tr>
                    <td><%= word.content %></td>
                    <td><%= word.choices.find_by(is_correct: true).content %></td>
                    <td>
                        <%= link_to "Edit", edit_admin_category_word_path(@category,word) , class: "btn btn-sm btn-warning"%>
                        <%= link_to "Remove",admin_category_word_path(@category,word) ,method: :delete, class: "btn btn-sm btn-danger"%>
                    </td>
                </tr>
                <% end %>
            </table>
            <div class="paginate text-center">
                <%= will_paginate @words%>
            </div>
        </div>
    </div>
</div>

app/views/admin/words/new.html.erb
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <span>Admin | <%= @category.title %> | Words</span>
                </div>
                <div class="col-sm-6 text-right">
                    <%= link_to "Back",admin_category_words_path(@category)%>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="container w-75">
                <%= render 'form'%>
            </div>
        </div>
    </div>
</div>

app/views/words/_user_info.html.erb
<div class="card">
    <div class="card-body text-center">
        <div class="avatar">
            <div class="default">
                <% if current_user.avatar? %>
                    <%= image_tag current_user.avatar.url, class: 'w-50 rounded-circle'%>
                <%else%>
                    <%= image_tag "/assets/11.svg", class: '',style: 'width: 90px; height: 90px;'%>
                <%end%>
            </div>
        </div>

        <h3 class="mb-0"><%= current_user.name%></h3>
        <div class="mb-15"><%= current_user.email%></div>

        <div class="mt-3">
            <%= link_to "View Profile", user_path(current_user) , class: "btn btn-sm btn-warning text-white"%>
            <%= link_to "Update Profile", edit_user_path(current_user) , class: "btn btn-sm btn-info text-white"%>
        </div>
    </div>
</div>

app/views/words/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <%=render 'user_info'%>
        </div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <h4>Words Learned</h4>
                </div>
                <div class="card-body">
                    <span class="dropdown">
                        <button class="btn btn-bordered dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Select Category
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <li><%= link_to "All Learned",words_path ,class: "dropdown-item w-100 "%></li>
                            <% @categories.each do |category|%>
                                <li><%= link_to category.title,words_path(cate: category.title) ,class: "dropdown-item w-100"%></li>
                            <%end%>
                        </div>
                    </span>
                    
                    <%if !@cate %>
                        <strong class="float-right h3"><span class="h5">Category: </span>All Categories</strong>
                    <%else%>
                        <%if !@lessons.any? %>
                            <strong class="float-right h3"><span class="h5">You haven't learned this category: </span><%= @cate %></strong>
                        <%else%>
                            <strong class="float-right h3"><span class="h5">Category: </span><%= @cate %></strong>
                        <%end%>
                        
                    <%end%>
                    <table class="table">
                        <tr>
                            <th>Word</th>
                            <th>Your Answer</th>
                            <th colspan="2">Correct Answer</th>
                        </tr>
                        <% @lessons.each do |lesson| %>
                            <% lesson.words.each do |word| %>
                                <tr>
                                    <td><%= word.content %></td>
                                    <td><%= word.choices.find_by(id: lesson.answers.find_by(word_id: word.id).choice_id).content %></td>
                                    <td><%= word.choices.find_by(is_correct: true).content %></td>
                                    <td>
                                        <% if word.choices.find_by(id: lesson.answers.find_by(word_id: word.id).choice_id).content == word.choices.find_by(is_correct: true).content%>
                                            <i class="fa fa-check text-success"></i>
                                        <%else%>
                                            <i class="fa fa-times text-danger"></i>
                                        <%end%>
                                    
                                    </td>
                                </tr>
                            <%end%>
                            
                        <%end%>
                        
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>