config/routes.rb
Rails.application.routes.draw do
  get 'votes/index'
  resources :replies
  resources :comments
  resources :activities do
    
    member do
      post 'upvote'
      delete 'downvote'
    end
  end
  namespace :admin do
    get 'users/index'
  end
  resources :relationships
  resources :words

  
  namespace :admin do
    resources :users do
      member do
        patch 'add'
        patch 'remove'
      end
    end
    resources :categories do
      resources :words
    end
  end
  
  resources :categories
  
  resources :lessons do
    resources :answers
  end
  resources :sessions
  resources :users do
    get 'dashboard'
    get 'liked_by'
    member do
      get 'following'
      get 'followers' 
    end
  end
  root 'pages#home'
  get 'categories/index'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
  default_scope { order(created_at: :desc) }
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  has_many :lessons, dependent: :destroy
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  has_many :answers, dependent: :destroy
  # validates :is_correct, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  has_many :replies

  validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity, as: :action, dependent: :destroy
  def correct_answers
    choices.where(is_correct: true).count
  end
  
  def next_word
    (category.words - words).first
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_one :activity, as: :action, dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }

  #REGEX = regular expression
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
            length: { maximum: 255 },
            format:{ with: EMAIL_REGEX},
            uniqueness: { case_sensitive: false}
  
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true

  mount_uploader :avatar, AvatarUploader
  has_many :lessons, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies
  def follow(other_user)
    Relationship.create(
      follower_id: id,            #current_user.id
      followed_id: other_user.id  #@user.id
    )
  end

  def active_relationships
    Relationship.where(follower_id: id)
  end


  def relationship(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def passive_relationships
    Relationship.where(followed_id: id)
  end

  def followers
    ids = passive_relationships.pluck(:follower_id)
    User.where(id: ids)
  end

  def following
    ids = active_relationships.pluck(:followed_id)
    User.where(id: ids)
  end
  
  def feed
    ids = following.pluck(:id)
    ids << id      #append | add the user_id to the array
    Activity.where(user_id: ids)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  validate :only_one_is_checked

  validates :content,presence: true, length: { maximum: 50 }
  private

  # validates choices: :content,uniqueness: { case_sensitive: false}
    def only_one_is_checked
      if choices.select{ |choice| choice.is_correct == true }.count !=1
        return errors.add :base, "Must have one correct choice"
      end
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :admin

  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 10)
  end
  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "category created!"
      redirect_to admin_categories_url
    else
      render 'new' 
    end
  end

  def edit
    @category = Category.find(params[:id])
    
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:success] = "Category updated!"
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      flash[:info] = "Category deleted."
      redirect_to request.referrer
    end
  end

  
  private
  def admin
    if !current_user.is_admin?
      flash[:danger] = "You can't access admin pages."
      redirect_to user_dashboard_url(current_user)
    end
  end

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @page = params[:learned]
    @ids = current_user.lessons.pluck(:category_id)
    if params[:learned].eql?("learned")
      @categories = Category.joins(:words).distinct.where(id: @ids).paginate(page: params[:page], per_page: 10)
    elsif params[:learned].eql?("notlearned")
      @categories = Category.joins(:words).distinct.where.not(id: @ids).paginate(page: params[:page], per_page: 10)
    else
      @categories = Category.joins(:words).distinct.paginate(page: params[:page], per_page: 10)
    end
  end
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out(user)
    session.delete(:user_id)
  end

  def logged_in?              #return true if current/user is not nil
    !current_user.nil?        #check if current_user is not nill
  end
  
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/categories/_error.html.erb
<% if @category.errors.any?%>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong><%= pluralize(@category.errors.count, "error") %></strong> 
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
        
    </div>
    
<% end %>

app/views/admin/categories/_form.html.erb
<%= form_for([:admin, @category]) do |f| %>
    <%= render 'error'%>
    <div class="form-group row">
        <div class="col-sm-2">
            <%= f.label :title %>
        </div>
        <div class="col-sm-10">
            <%= f.text_field :title, class: 'form-control' %>
        </div>
        
    </div>
    <div class="form-group row">
        <div class="col-sm-2">
            <%= f.label :description %>
        </div>
        <div class="col-sm-10">
            <%= f.text_area :description, class: 'form-control' %>
        </div>
    </div>

    <div class="form-group text-center">
        <%= f.submit 'Save Category',class: 'btn btn-success'%>
    </div>
<% end %>

app/views/admin/categories/edit.html.erb
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <span>Admin | Categories | Edit</span>
                </div>
                <div class="col-sm-6 text-right">
                    <%= link_to "Back",admin_categories_path%>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="container w-75">
                <%= render 'form'%>
            </div>
                
        </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <span>Admin | Categories</span>
                </div>
                <div class="col-sm-6 text-right">
                    <%= link_to "Add Category",new_admin_category_path,class: "btn btn-sm btn-success"%>
                </div>
            </div>
        </div>
        <table class="table">
            <tr>
                <th class="">Title</th>
                <th class="">Description</th>
                <th class="text-center">Words</th>
                <th class="">Action</th>
            </tr>
            <% @categories.each do |category|%>
                <tr>
                    <td>
                        <%= category.title %>
                    </td>
                    <td>
                        <%= category.description %>
                    </td>
                    <td class="text-center">
                        <%= category.words.count %>
                    </td>

                    <td>
                        <%= link_to "Add Word",admin_category_words_path(category),class: "btn btn-sm btn-primary"%>
                        <%= link_to "Edit",edit_admin_category_path(category),class: "btn btn-sm btn-warning"%>
                        <%= link_to "Remove",admin_category_path(category),method: :delete,class: "btn btn-sm btn-secondary"%>
                    </td>
                </tr>
            <% end %>
            
        </table>
        <div class="paginate text-center">
            <%= will_paginate @categories%>
        </div>
    </div>
</div>

app/views/admin/categories/new.html.erb
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-sm-6">
                    <span>Admin | Categories</span>
                </div>
                <div class="col-sm-6 text-right">
                    <%= link_to "Back",admin_categories_path%>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="container w-75">
                <%= form_for([:admin, @category]) do |f| %>

                
                    <%= render 'error'%>
                    <div class="form-group row">
                        <div class="col-sm-2">
                            <%= f.label :title %>
                        </div>
                        <div class="col-sm-10">
                            <%= f.text_field :title, class: 'form-control' %>
                        </div>
                        
                    </div>
                    <div class="form-group row">
                        <div class="col-sm-2">
                            <%= f.label :description %>
                        </div>
                        <div class="col-sm-10">
                            <%= f.text_area :description, class: 'form-control' %>
                        </div>
                    </div>

                    <div class="form-group text-center">
                        <%= f.submit 'Save Category',class: 'btn btn-success'%>
                    </div>
                <% end %>
            </div>
                
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="container">
    <ul class="nav nav-pills nav-warning float-right justify-content-end">
        <li class="nav-item">
            <%=link_to "All", categories_path, class: "nav-link #{'active' if !@page}"%>
        </li>
        <li class="nav-item">
            <%=link_to "Learned", categories_path(learned: "learned"), class: "nav-link #{'active' if @page.eql?('learned')}"%>
        </li>
        <li class="nav-item">
            <%=link_to "Not Learned", categories_path(learned: "notlearned"), class: "nav-link #{'active' if @page.eql?('notlearned')}"%>
        </li>
    </ul>
    <h1 class="">Categories(<%=@categories.count%>)</h1>
    <hr>

    
    
    <div class="row">
        <% @categories.each do |category|%>
            <%# if category.words.count != 0 %>
                <div class="col-md-6">
                    <div class="card my-3">
                        <div class="card-body">
                            <strong class="h2"><%= category.title%></strong><br>
                            <div class="mt-3 mb-5">
                                <strong>[<%= pluralize(category.words.count, "word")%>] </strong><span><%=category.description%></span>
                            </div>
                            
                            <%#if category.lessons.find_by(user_id: current_user.id).result == nil %>
                            <% if category.lessons.find_by(user_id: current_user.id) && category.lessons.find_by(user_id: current_user.id).answers.count != category.words.count %>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <%= button_to "Continue",new_lesson_answer_path(lesson_id: category.lessons.find_by(user_id: current_user.id).id),method: :get,class: "btn btn-info text-white w-100"%>
                                    </div>
                                    <div class="col-sm-6">
                                        <%= button_to "Restart",lesson_path(category.lessons.find_by(user_id: current_user.id)),method: :delete,class: "btn btn-success text-white w-100"%>
                                    </div>
                                </div>
                                
                            <% elsif category.lessons.find_by(user_id: current_user.id) %>
                                <div class="container">
                                    <%= link_to "Show Result", lesson_path(category.lessons.find_by(user_id: current_user.id)), class: "btn btn-outline-secondary w-100"%>
                                </div>

                            <% else %>
                                <div class="container">
                                    <%= button_to "Learn",lessons_path(category_id:category.id),class: "btn btn-primary text-white w-100"%>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            <%# end %>
        <%end%>
    </div>
    <div class="paginate text-center">
        <%= will_paginate @categories%>
    </div>
</div>