config/routes.rb
Rails.application.routes.draw do
  get 'votes/index'
  resources :replies
  resources :comments
  resources :activities do
    
    member do
      post 'upvote'
      delete 'downvote'
    end
  end
  namespace :admin do
    get 'users/index'
  end
  resources :relationships
  resources :words

  
  namespace :admin do
    resources :users do
      member do
        patch 'add'
        patch 'remove'
      end
    end
    resources :categories do
      resources :words
    end
  end
  
  resources :categories
  
  resources :lessons do
    resources :answers
  end
  resources :sessions
  resources :users do
    get 'dashboard'
    get 'liked_by'
    member do
      get 'following'
      get 'followers' 
    end
  end
  root 'pages#home'
  get 'categories/index'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
  default_scope { order(created_at: :desc) }
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  has_many :lessons, dependent: :destroy
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  has_many :answers, dependent: :destroy
  # validates :is_correct, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  has_many :replies

  validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity, as: :action, dependent: :destroy
  def correct_answers
    choices.where(is_correct: true).count
  end
  
  def next_word
    (category.words - words).first
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_one :activity, as: :action, dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }

  #REGEX = regular expression
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
            length: { maximum: 255 },
            format:{ with: EMAIL_REGEX},
            uniqueness: { case_sensitive: false}
  
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true

  mount_uploader :avatar, AvatarUploader
  has_many :lessons, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies
  def follow(other_user)
    Relationship.create(
      follower_id: id,            #current_user.id
      followed_id: other_user.id  #@user.id
    )
  end

  def active_relationships
    Relationship.where(follower_id: id)
  end


  def relationship(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def passive_relationships
    Relationship.where(followed_id: id)
  end

  def followers
    ids = passive_relationships.pluck(:follower_id)
    User.where(id: ids)
  end

  def following
    ids = active_relationships.pluck(:followed_id)
    User.where(id: ids)
  end
  
  def feed
    ids = following.pluck(:id)
    ids << id      #append | add the user_id to the array
    Activity.where(user_id: ids)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  validate :only_one_is_checked

  validates :content,presence: true, length: { maximum: 50 }
  private

  # validates choices: :content,uniqueness: { case_sensitive: false}
    def only_one_is_checked
      if choices.select{ |choice| choice.is_correct == true }.count !=1
        return errors.add :base, "Must have one correct choice"
      end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def add
    @user = User.find(params[:id])
    if @user.update(is_admin: true)
      flash[:info] = "Added as Admin."
      redirect_to request.referrer
    end
  end
  
  def remove
    @user = User.find(params[:id])
    if @user.update(is_admin: false)
      flash[:success] = "Removed as Admin."
      redirect_to request.referrer
    end
  end

  private
  def admin
    if !current_user.is_admin?
      flash[:danger] = "You can't access admin pages."
      redirect_to user_dashboard_url(current_user)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login, only: [:new, :create],raise: false

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:info] = "Please log in."
      redirect_to login_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "Your setting has been updated."
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @lessons = @user.lessons.all
    @howmany = 0
    @activities = Activity.where(user_id: @user.id).paginate(page: params[:page], per_page: 10)
    @comment = Comment.new
  end

  def dashboard
    @users = User.all
    @user = current_user
    @lessons = current_user.lessons.all
    @howmany = 0
    @activities = @user.feed.paginate(page: params[:page], per_page: 10)
    @comment = Comment.new
  end

  def following
    @user = User.find(params[:id])
    @lessons = @user.lessons
    @howmany = 0
    @users = @user.following.paginate(page: params[:page], per_page: 5)
  end
  def followers
    @user = User.find(params[:id])
    @lessons = @user.lessons
    @howmany = 0
    @users = @user.followers.paginate(page: params[:page], per_page: 5)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :avatar, :password, :password_confirmation)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out(user)
    session.delete(:user_id)
  end

  def logged_in?              #return true if current/user is not nil
    !current_user.nil?        #check if current_user is not nill
  end
  
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/users/index.html.erb
<div class="container">
    <h1 class="text-center">User Management</h1>
    <hr>

    
    
    <div class="row">
        <% @users.each do |user|%>
            <div class="col-md-6">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="media">
                            <% if user.avatar? %>
                                <%= image_tag user.avatar.url, class: 'rounded-circle',style: 'width: 90px;'%>
                            <%else%>
                                <%= image_tag "/assets/11.svg", class: '',style: 'width: 90px; height: 90px;'%>
                            <%end%>
                            <div class="media-body pt-4">
                                <span class="h5 pl-3"><%= link_to user.name, user_path(user)%></span>
                                <div class="float-right">
                                    <% if user!=current_user%>
                                        <% if user.is_admin? %>
                                            <%= button_to 'Remove as Admin',remove_admin_user_path(user),
                                                method: :patch,
                                                class:"btn btn-danger"
                                            %>
                                        <%else%>
                                            <%= button_to 'Add as Admin',add_admin_user_path(user),
                                                method: :patch,
                                                class:"btn btn-primary" 
                                            %>
                                        <%end%>
                                    <%end%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
    <div class="paginate text-center">
        <%= will_paginate @users%>
    </div>
</div>

app/views/users/_activity.html.erb
<% @activities.each_with_index do |activity,index|%>
    <div id="#{index}">
        <div class="media mb-4">
            <div class="avatarsquare">
                <div class="default">
                    <% if activity.user.avatar? %>
                        <%= image_tag activity.user.avatar.url,style: 'width: 50px; height: 50px;'%>
                    <%else%>
                        <%= image_tag "/assets/11.svg", class: '',style: 'width: 50px; height: 50px;'%>
                    <%end%>
                </div>
            </div>
            <div class="media-body ml-2 row">
                <div class="col-md-5">
                    <strong>
                        <% if activity.user == current_user %>
                            <%=link_to "You",user_path(activity.user),class: "text-muted"%>
                        <% else %>
                            <%=link_to activity.user.name,user_path(activity.user),class: "text-muted"%>
                        <% end %>
                    </strong>
                    <span>
                        <% if activity.action_type == "Relationship" %>
                            followed
                            <%=link_to @users.find_by(id: activity.action.followed_id).name,user_path(@users.find_by(id: activity.action.followed_id)),class: "badge badge-secondary"%>
                        <% else %>
                            learned <%=activity.action.result%> of <%=activity.action.choices.count%>
                            <%=link_to activity.action.category.title,lesson_path(activity.action),class: "badge badge-primary"%>
                        <% end %>
                    </span>
                    <div>
                        <small class="text-muted"><%= time_ago_in_words(activity.created_at) %></small>
                    </div>
                </div>
                
                <% if activity.user != current_user %>

                    <div class="col-md-4">
                        <%= link_to comments_path(activity_id: activity.id) do %>
                            <%= fa_icon 'comment',class: "text-secondary"%>
                            <%= activity.comments.count%>
                        <% end %>
                        <% if activity.votes.find_by(user_id: current_user.id) %>
                            <%= link_to downvote_activity_path(activity), method: :delete do %>
                                <%= fa_icon 'heart',class: "text-danger"%>
                            <% end %>
                            <%= link_to votes_index_path(activity_id: activity.id) do %>
                                <%= pluralize(activity.votes.count, "Like") %>
                            <% end %>
                        <% else %>
                            <%= link_to upvote_activity_path(activity), method: :post do %>
                                <%= fa_icon 'heart',class: "text-secondary"%>
                            <% end %>
                            <%= link_to votes_index_path(activity_id: activity.id) do %>
                                <%= pluralize(activity.votes.count, "Like") %>
                            <% end %>
                        <% end %>
                    </div>
                    
                    <div class="col-md-3 text-right">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal_<%=activity.id%>">
                        Comment
                        </button>

                        <!-- Modal -->
                        <%= form_for @comment do |f|%>
                            
                            <div class="modal fade" id="exampleModal_<%=activity.id%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Please write your comment here!</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="row">
                                                <div class="col-12">
                                                    <div class="form-group">
                                                        <div class="">
                                                            <%= f.text_area :content, class: 'form-control w-100 mx-auto' %>
                                                        </div>
                                                        <%= f.hidden_field :activity_id, value: activity.id%>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            <div class="ml-2">
                                                <%= f.submit 'Post',class: 'btn btn-primary form-control'%>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </div>

                <% else %>
                    <%= link_to comments_path(activity_id: activity.id) do %>
                        <%= fa_icon 'comment',class: "text-secondary"%>
                        <%= activity.comments.count%>
                    <% end %>

                    <div class="col-md-5">
                        <%= link_to votes_index_path(activity_id: activity.id) do %>
                            <%= pluralize(activity.votes.count, "Like") %>
                        <% end %>
                        
                    </div>
                <% end %>
            </div>
        </div>
    </div>
    
<% end %>

app/views/users/_all_user_info.html.erb
<div class="card">
    <div class="card-body text-center">
        <div class="avatar">
            <div class="default">
                <% if @user.avatar? %>
                    <%= image_tag @user.avatar.url, class: 'w-50 rounded-circle'%>
                <%else%>
                    <%= image_tag "/assets/11.svg", class: '',style: 'width: 90px; height: 90px;'%>
                <%end%>
            </div>
        </div>

        <h3 class="mb-0"><%= @user.name%></h3>
        <div class="mb-15"><%= @user.email%></div>

        <div class="mt-3">
            <%= link_to "View Profile", "#" , class: "btn btn-sm btn-warning text-white"%>
            <%= link_to "Update Profile", "#" , class: "btn btn-sm btn-info text-white"%>
        </div>
    </div>
</div>

<div class="card mt-4">
    <div class="card-body">
        <div class="text-center">
            <div class="d-inline-block mr-4">
                <%= link_to "2", "#" %>
                <span>following</span>
            </div>
            <div class="d-inline-block">
                <%= link_to "2", "#" %>
                <span>followers</span>
            </div>
        </div>
    </div>
</div>

<% @lessons.each do |lesson| %>
    <% @howmany += lesson.words.count %>
<% end %>
<div class="card mt-4">
    <div class="card-body text-center">
        <% if @user == current_user %>
            <%= link_to "#{@howmany} words learned", words_path , class: "btn btn-info btn-block no-border p-5"%>
        <% else %>
            <%= pluralize(@howmany, "word") %>
            <span>learned</span>
        <% end %>
    </div>
</div>

app/views/users/_error_messages.html.erb
<% if para.errors.any? %>
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong><%= pluralize(para.errors.count, "error") %></strong> 
        <ul>
        <% para.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
        
    </div>
    
<% end %>

app/views/users/_follow_button.html.erb
<% if current_user.relationship(user) %>
    <%= button_to 'Unfollow',relationship_path(user),
        params: {followed_id: user.id},
        method: :delete,
        class:"btn btn-danger"
    %>
<%else%>
    <%= button_to 'Follow',relationships_path,
        params: {followed_id: user.id},
        class:"btn btn-primary" 
    %>
<%end%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <%= render 'error_messages',para: @user%>
    <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :email %><br>
        <%= f.email_field :email, class: 'form-control' %>
    </div>


    <div class="form-group">
        <%= f.label :password %><br>
        <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    
    <br>

    <div class="form-group">
        <%= f.submit 'Create an account',class: 'btn btn-primary w-100'%>
    </div>
<% end %>

app/views/users/_user_info.html.erb
<div class="card">
    <div class="card-body text-center">
        <div class="avatar">
            <div class="default">
                <% if @user.avatar? %>
                    <%= image_tag @user.avatar.url, class: 'w-50 rounded-circle'%>
                <%else%>
                    <%= image_tag "/assets/11.svg", class: '',style: 'width: 90px; height: 90px;'%>
                <%end%>
            </div>
        </div>

        <h3 class="mb-0"><%= @user.name%></h3>
        <div class="mb-3"><%= @user.email%></div>
        <% if @user!=current_user%>
            <%=render 'users/follow_button',user: @user%>
        <%end%>
    </div>
</div>

<div class="card mt-4">
    <div class="card-body">
        <div class="text-center">
            <div class="d-inline-block mr-4">
                <%= link_to @user.active_relationships.count, following_user_path%>
                <span>following</span>
            </div>
            <div class="d-inline-block">
                <%= link_to @user.passive_relationships.count, followers_user_path%>
                <span>followers</span>
            </div>
        </div>
    </div>
</div>

<% @lessons.each do |lesson| %>
    <% @howmany += lesson.words.count %>
<% end %>
<div class="card mt-4">
    <div class="card-body text-center">
        <% if @user == current_user %>
            <%= link_to "#{@howmany} words learned", words_path , class: "btn btn-info btn-block no-border p-5"%>
        <% else %>
            <%= pluralize(@howmany, "word") %>
            <span>learned</span>
        <% end %>
    </div>
</div>

app/views/users/dashboard.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <%=render 'all_user_info'%>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4>Activity Feed</h4>
                </div>
                <div class="card-body">
                    <%=render 'activity'%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container w-25 mx-auto">
    <h1 class="text-center">Setting</h1>
    <hr>

    <%= form_for(@user) do |f| %>
        <%= render 'error_messages',para: @user%>
        <div class="form-group">
            <%= f.label :avatar %><br>
            <%= f.file_field :avatar, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :email %><br>
            <%= f.email_field :email, class: 'form-control' %>
        </div>

        <% if logged_in? %>
            <div class="form-group">
                <%= f.label :password %><br>
                <%= f.password_field :password, class: 'form-control' %>
            </div>
        <% else %>
            <div class="form-group">
                <%= f.label :password %><br>
                <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :password_confirmation %><br>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
        <% end %>
        
        <br>

        <div class="form-group">
            <%= f.submit 'Update',class: 'btn btn-primary w-100'%>
        </div>
    <% end %>
</div>

app/views/users/followers.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <%=render 'user_info'%>
        </div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <h4>Followers</h4>
                </div>
                <div class="card-body">
                    <% @users.each do |user| %>
                        <div class="media mb-4 border-bottom pb-3">
                            <% if user.avatar? %>
                                <%= image_tag user.avatar.url, class: 'rounded-circle',style: 'width: 90px;'%>
                            <%else%>
                                <%= image_tag "/assets/11.svg", class: '',style: 'width: 90px; height: 90px;'%>
                            <%end%>
                            <div class="media-body pt-4">
                                <span class="h5 pl-3"><%= link_to user.name,user_path(user)%></span>
                                <div class="float-right">
                                    <% if user!=current_user%>
                                        <%=render 'follow_button',user: user%>
                                    <%end%>
                                </div>
                                
                            </div>
                            
                        </div>
                    <% end %>
                    <div class="paginate text-center">
                        <%= will_paginate @users%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/following.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <%=render 'user_info'%>
        </div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <h4>Following</h4>
                </div>
                <div class="card-body">
                    <% @users.each do |user| %>
                        <div class="media mb-4 border-bottom pb-3">
                            <% if user.avatar? %>
                                <%= image_tag user.avatar.url, class: 'rounded-circle',style: 'width: 90px;'%>
                            <%else%>
                                <%= image_tag "/assets/11.svg", class: '',style: 'width: 90px; height: 90px;'%>
                            <%end%>
                            <div class="media-body pt-4">
                                <span class="h5 pl-3"><%= link_to user.name,user_path(user)%></span>
                                <div class="float-right">
                                    <% if user!=current_user%>
                                        <%=render 'follow_button',user: user%>
                                    <%end%>
                                </div>
                                
                            </div>
                        </div>
                    <% end %>
                    <div class="paginate text-center">
                        <%= will_paginate @users%>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <h1 class="text-center">Users</h1>
    <hr>

    
    
    <div class="row">
        <% @users.each do |user|%>
            <div class="col-md-6">
                <div class="card my-3">
                    <div class="card-body">
                        <div class="media">
                            <% if user.avatar? %>
                                <%= image_tag user.avatar.url, class: 'rounded-circle',style: 'width: 90px;'%>
                            <%else%>
                                <%= image_tag "/assets/11.svg", class: '',style: 'width: 90px; height: 90px;'%>
                            <%end%>
                            <div class="media-body pt-4">
                                <span class="h5 pl-3"><%= link_to user.name, user_path(user)%></span>
                                <div class="float-right">
                                    <% if user!=current_user%>
                                        <%=render 'follow_button',user: user%>
                                    <%end%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <%end%>
    </div>
    <div class="paginate text-center">
        <%= will_paginate @users%>
    </div>
</div>

app/views/users/new.html.erb
<div class="container w-25 mx-auto mb-5">
    <h1 class="text-center">Sign up</h1>
    <p class="text-center">Join us for free!</p>
    <hr>
    <%=render 'form'%>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-4">
            <%=render 'user_info'%>
        </div>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-header">
                    <h4><%=@user.name%>'s Activity</h4>
                </div>
                <div class="card-body">
                    <%=render 'activity'%>
                </div>
            </div>
        </div>
    </div>
</div>