config/routes.rb
Rails.application.routes.draw do
  get 'votes/index'
  resources :replies
  resources :comments
  resources :activities do
    
    member do
      post 'upvote'
      delete 'downvote'
    end
  end
  namespace :admin do
    get 'users/index'
  end
  resources :relationships
  resources :words

  
  namespace :admin do
    resources :users do
      member do
        patch 'add'
        patch 'remove'
      end
    end
    resources :categories do
      resources :words
    end
  end
  
  resources :categories
  
  resources :lessons do
    resources :answers
  end
  resources :sessions
  resources :users do
    get 'dashboard'
    get 'liked_by'
    member do
      get 'following'
      get 'followers' 
    end
  end
  root 'pages#home'
  get 'categories/index'
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
  default_scope { order(created_at: :desc) }
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  has_many :lessons, dependent: :destroy
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
  has_many :answers, dependent: :destroy
  # validates :is_correct, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  has_many :replies

  validates :content, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity, as: :action, dependent: :destroy
  def correct_answers
    choices.where(is_correct: true).count
  end
  
  def next_word
    (category.words - words).first
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_one :activity, as: :action, dependent: :destroy
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }

  #REGEX = regular expression
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
            length: { maximum: 255 },
            format:{ with: EMAIL_REGEX},
            uniqueness: { case_sensitive: false}
  
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true

  mount_uploader :avatar, AvatarUploader
  has_many :lessons, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :replies
  def follow(other_user)
    Relationship.create(
      follower_id: id,            #current_user.id
      followed_id: other_user.id  #@user.id
    )
  end

  def active_relationships
    Relationship.where(follower_id: id)
  end


  def relationship(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def passive_relationships
    Relationship.where(followed_id: id)
  end

  def followers
    ids = passive_relationships.pluck(:follower_id)
    User.where(id: ids)
  end

  def following
    ids = active_relationships.pluck(:followed_id)
    User.where(id: ids)
  end
  
  def feed
    ids = following.pluck(:id)
    ids << id      #append | add the user_id to the array
    Activity.where(user_id: ids)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :answers, dependent: :destroy
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  validate :only_one_is_checked

  validates :content,presence: true, length: { maximum: 50 }
  private

  # validates choices: :content,uniqueness: { case_sensitive: false}
    def only_one_is_checked
      if choices.select{ |choice| choice.is_correct == true }.count !=1
        return errors.add :base, "Must have one correct choice"
      end
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out(user)
    session.delete(:user_id)
  end

  def logged_in?              #return true if current/user is not nil
    !current_user.nil?        #check if current_user is not nill
  end
  
  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer py-3 bg-dark text-center mt-5 w-100">
    <div class="container">
        <span class="text-muted">E-Learning @ Ren</span>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container">
        <%= link_to "E-LEARNING",root_path, class:"navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav ml-auto mb-2 mb-md-0">
                
                <% if logged_in? %>
                    <li class="nav-item">
                        <%= link_to "Dashboard",user_dashboard_path(current_user), class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Categories",categories_path, class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Members",users_path, class:"nav-link"%>
                    </li>
                    <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"><%= current_user.name %></a>

                    <div class="dropdown-menu">
                        <%= link_to "Profile",user_path(current_user) , class: "dropdown-item" %>
                        <%= link_to "Settings",edit_user_path(current_user), class: "dropdown-item" %>
                        <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>

                        <% if current_user.is_admin? %>
                            <div class="dropdown-divider"></div>
                            <%= link_to "Manage Categories",admin_categories_path, class: "dropdown-item" %>
                            <%= link_to "User Management",admin_users_path, class: "dropdown-item" %>
                        <% end %>

                    </div>
                </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to "Sign up",new_user_path, class:"nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Log in",login_path, class:"nav-link"%>
                    </li>
                <% end %>
                
            </ul>
        </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ELearningRen</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body style="margin-top:72px;" class="footerFixed">
        <%= render 'layouts/header' %>

        <% if flash.any? %>
            <% flash.each do |type, msg|%>
            <div class="container">
                <div class="alert alert-<%= type %>">
                    <div><%= msg %></div>
                </div>
            </div>
            
            <% end %>
        <% end %>

        <%= yield %>
        <%= render 'layouts/footer' %>
    </body>
</html>